[package]
name = "password"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
rand = "0.8.5"
rpassword = "7.3.1"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
chrono = "0.4.35"
gloo-timers = "0.3.0"
